name: ci

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
      -
        name: Build
        run: |
          docker build  -f App.Server/Dockerfile --platform linux/arm64 -t paulyk/dockerize-1 --push .