name: test_1

on: [push]    

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}          
      -
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
      -
        name: Build
        run: |
          docker build  -f App.Server/Dockerfile --platform linux/arm64,linux/amd64 -t paulyk/dockerize-1 --push .