name: test_1

on: [push]    

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: |
          echo Create Azure Container
          echo Figma Variants
          echo ${{ secrets.DOCKER_HUB_USERNAME }}
      - 
        name: second step
        run: echo "The workflow is done"
