name: test_1

on: [push]    

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}          
      -
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: App.Server/Dockerfile
          platforms: linux/arm64,linux/amd64
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dockerize-1:latest
          push: true

#          docker build  -f App.Server/Dockerfile --platform linux/arm64,linux/amd64 -t paulyk/dockerize-1 --push .